#ifndef FILECONTROL_H
#define FILECONTROL_H
#include <stdio.h>

typedef struct C_FILE
{
	int num_of_lines;
	int *num_of_elements_per_line;
	int **data;
}C_FILE;


int fileGetInt(FILE*);		// Reads an int until ' ', '\n', '|0' are met.
char* fileGetLine(FILE*);	//	Reads a string until ' ', '\n', '|0' are met.

void fileInputGenerator();		//	Input file generator. File is input.in and data is taken from user. (Can be customized to random generators.)
C_FILE* fileReadInput(FILE*);	//	Reads an input file generated by fileInputGenerator() into C_FILE and returns it.

void fileOutputGenerator(int, int*, int**);		//	Output file generator. File is output.out and data is provided as arguments. (Data type can be customized.)
C_FILE* fileReadOutput(FILE*);					//	Reads an output file generated by fileOutputGenerator() into C_FILE and returns it.

void filePrint(C_FILE*);

#endif
